[package]
name = "bmp-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
bmp-domain = { path = "../bmp-domain" }
rusqlite.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
chrono.workspace = true
thiserror.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs = "5.0"

[dev-dependencies]
tempfile.workspace = true
